matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode11.5
      install:
        - gem install xcpretty
      before_script:
        - cd objc
      script:
        - set -o pipefail
        - xcodebuild -version
        - xcodebuild -showsdks
        - xcodebuild
          -workspace "objc.xcworkspace"
          -scheme "LeetCode"
          -sdk "macosx10.15"
          -destination "arch=x86_64"
          -configuration Debug
          ONLY_ACTIVE_ARCH=NO
          test
          | xcpretty -c

    - language: swift
      os: osx
      osx_image: xcode11.5
      before_script:
        - cd swift
      script:
        - set -o pipefail
        - swift test
