matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode11.5
      env:
        global:
          - DESTINATION="arch=x86_64"
          - LC_CTYPE=en_US.UTF-8
          - LANG=en_US.UTF-8
          - SCHEME_NAME="LeetCode"
          - SDK=macosx10.15.4
          - WORKSPACE_NAME="objc"
      install:
        - gem install xcpretty
      before_script:
        - cd objc
      script:
        - set -o pipefail
        - xcodebuild -version
        - xcodebuild -showsdks
        - xcodebuild
          -workspace "$WORKSPACE_NAME.xcodeproj"
          -scheme "$FRAMEWORK_NAME $SCHEME"
          -sdk "$SDK"
          -destination "$DESTINATION"
          -configuration Debug
          ONLY_ACTIVE_ARCH=NO
          test
          | xcpretty -c
